name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: cvbuilder
        options: >-
          --health-cmd="pg_isready -U postgres" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/cvbuilder
      NEXTAUTH_SECRET: testsecret
      NEXT_PUBLIC_APP_URL: http://localhost:3000
      NEXTAUTH_URL: http://localhost:3000
      DISABLE_PDF: 'true'
      CI: 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Generate Prisma
        run: pnpm prisma:generate
      - name: Migrate DB
        run: pnpm prisma:deploy
      - name: Seed
        run: pnpm prisma:seed
      - name: Lint
        run: pnpm lint
      - name: Typecheck
        run: pnpm typecheck
      - name: Unit tests
        run: pnpm test
      - name: Build
        run: pnpm build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: E2E tests
        run: pnpm e2e
